In [1]:
import pandas as pd

In [2]:
dataset = pd.read_csv('webserverlog.csv')

In [3]:
dataset

Host Log Name            Date Time Time Zone Method  \
0       192.168.99.1        -  2020-06-26 09:59:05  GMT+0530    GET   
1       192.168.99.1        -  2020-06-26 09:59:06  GMT+0530    GET   
2       192.168.99.1        -  2020-06-26 10:00:03  GMT+0530    GET   
3       192.168.99.1        -  2020-06-26 10:00:03  GMT+0530    GET   
4       192.168.99.1        -  2020-06-26 10:00:03  GMT+0530    GET   
...              ...      ...                  ...       ...    ...   
39854  192.168.1.103        -  2020-06-30 16:14:59  GMT+0530    GET   
39855  192.168.1.103        -  2020-06-30 16:14:59  GMT+0530    GET   
39856  192.168.1.103        -  2020-06-30 16:14:59  GMT+0530    GET   
39857  192.168.1.103        -  2020-06-30 16:14:59  GMT+0530    GET   
39858  192.168.1.103        -  2020-06-30 16:14:59  GMT+0530    GET   

                          URL  Response Code  Bytes Sent  \
0                           /            200          36   
1                /favicon.ico            404         209   
2                  /?NZBW=RGN            200          36   
3                  /?NZBW=RGN            200          36   
4      /?ZJXVIHEVAZ=NXXRAGHFQ            200          36   
...                       ...            ...         ...   
39854                       /            200          36   
39855                       /            200          36   
39856                       /            200          36   
39857                       /            200          36   
39858                       /            200          36   

                                                Referer  \
0                                                     -   
1                                http://192.168.99.102/   
2                   http://www.google.com/?q=MZPDYWETQF   
3                   http://www.google.com/?q=MZPDYWETQF   
4      http://engadget.search.aol.com/search?q=XJPTOKGP   
...                                                 ...   
39854                                                 -   
39855                                                 -   
39856                                                 -   
39857                                                 -   
39858                                                 -   

                                              User Agent  
0      Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/53...  
1      Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/53...  
2      Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US...  
3      Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US...  
4      Mozilla/4.0 (compatible; MSIE 8.0; Windows NT ...  
...                                                  ...  
39854                                        curl/7.61.1  
39855                                        curl/7.61.1  
39856                                        curl/7.61.1  
39857                                        curl/7.61.1  
39858                                        curl/7.61.1  

[39859 rows x 10 columns]

In [4]:
newdata = dataset.drop(['Log Name' , 'Time Zone' , 'Method' , 'Referer' , 'Bytes Sent', 'User Agent'], axis=1)

In [5]:
newdata

Host            Date Time                     URL  \
0       192.168.99.1  2020-06-26 09:59:05                       /   
1       192.168.99.1  2020-06-26 09:59:06            /favicon.ico   
2       192.168.99.1  2020-06-26 10:00:03              /?NZBW=RGN   
3       192.168.99.1  2020-06-26 10:00:03              /?NZBW=RGN   
4       192.168.99.1  2020-06-26 10:00:03  /?ZJXVIHEVAZ=NXXRAGHFQ   
...              ...                  ...                     ...   
39854  192.168.1.103  2020-06-30 16:14:59                       /   
39855  192.168.1.103  2020-06-30 16:14:59                       /   
39856  192.168.1.103  2020-06-30 16:14:59                       /   
39857  192.168.1.103  2020-06-30 16:14:59                       /   
39858  192.168.1.103  2020-06-30 16:14:59                       /   

       Response Code  
0                200  
1                404  
2                200  
3                200  
4                200  
...              ...  
39854            200  
39855            200  
39856            200  
39857            200  
39858            200  

[39859 rows x 4 columns]

In [6]:
from sklearn.preprocessing import OneHotEncoder, LabelEncoder

In [7]:
X = newdata.iloc[:,:]

In [8]:
x = X.to_numpy()

In [9]:
x

array([['192.168.99.1', '2020-06-26 09:59:05', '/', 200],
       ['192.168.99.1', '2020-06-26 09:59:06', '/favicon.ico', 404],
       ['192.168.99.1', '2020-06-26 10:00:03', '/?NZBW=RGN', 200],
       ...,
       ['192.168.1.103', '2020-06-30 16:14:59', '/', 200],
       ['192.168.1.103', '2020-06-30 16:14:59', '/', 200],
       ['192.168.1.103', '2020-06-30 16:14:59', '/', 200]], dtype=object)

In [10]:
label = LabelEncoder()

In [11]:
IP = label.fit_transform(x[:,0])

In [12]:
IP

array([6, 6, 6, ..., 0, 0, 0])

In [13]:
Date = label.fit_transform(x[:,1])

In [14]:
Date

array([  0,   1,   2, ..., 660, 660, 660])

In [15]:
URL = label.fit_transform(x[:,2])

In [16]:
RC = label.fit_transform(x[:,3])

In [17]:
df1 = pd.DataFrame(IP, columns=['IP'])

In [18]:
df2 = pd.DataFrame(Date, columns=['DATE'])

In [19]:
df3 = pd.DataFrame(URL, columns=['URL'])

In [20]:
df4 = pd.DataFrame(RC, columns=['Response Code'])

In [21]:
frames = [df1, df2, df3, df4]

In [22]:
result = pd.concat(frames, axis=1 )

In [23]:
result

IP  DATE    URL  Response Code
0       6     0      0              0
1       6     1  10279              2
2       6     2   5469              0
3       6     2   5469              0
4       6     2  10061              0
...    ..   ...    ...            ...
39854   0   660      0              0
39855   0   660      0              0
39856   0   660      0              0
39857   0   660      0              0
39858   0   660      0              0

[39859 rows x 4 columns]

In [24]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

In [25]:
data_scaled = sc.fit_transform(result)

In [26]:
data_scaled

array([[ 8.14867689e-01, -1.10731953e+00, -7.87514196e-01,
        -1.63609788e-02],
       [ 8.14867689e-01, -1.10263387e+00,  2.29898464e+00,
         8.15001706e+01],
       [ 8.14867689e-01, -1.09794820e+00,  8.54674941e-01,
        -1.63609788e-02],
       ...,
       [-2.07162796e+00,  1.98521769e+00, -7.87514196e-01,
        -1.63609788e-02],
       [-2.07162796e+00,  1.98521769e+00, -7.87514196e-01,
        -1.63609788e-02],
       [-2.07162796e+00,  1.98521769e+00, -7.87514196e-01,
        -1.63609788e-02]])

In [27]:
from sklearn.cluster import KMeans

In [28]:
model = KMeans(n_clusters=10)

In [29]:
pred  = model.fit_predict(data_scaled)

In [30]:
dataset_scaled = pd.DataFrame(data_scaled, columns=['IP', 'Date', 'URL', 'Response Code'])

In [31]:
dataset_scaled['mycluster'] = pred

In [32]:
ips = [dataset['Host'], result['IP']]
ips_result = pd.concat(ips, axis=1)

In [33]:
ips_result

Host  IP
0       192.168.99.1   6
1       192.168.99.1   6
2       192.168.99.1   6
3       192.168.99.1   6
4       192.168.99.1   6
...              ...  ..
39854  192.168.1.103   0
39855  192.168.1.103   0
39856  192.168.1.103   0
39857  192.168.1.103   0
39858  192.168.1.103   0

[39859 rows x 2 columns]

In [34]:
def CountFrequency(my_list, ip_label): 
  
    # Creating an empty dictionary  
    freq = {} 
    for item in my_list: 
        if (item in freq): 
            freq[item] += 1
        else: 
            freq[item] = 1
    max_freq = 0
    max_key = 0
    for key, value in freq.items(): 
        if value > max_freq:
            max_freq = value
            max_key = key
    
    return ip_label[my_list.index(max_key)]


In [40]:
res = CountFrequency(ips_result['IP'].tolist(), ips_result['Host'].tolist())

In [41]:
res = str(res)

In [42]:
file1 = open("blockIP.txt","w")
file1.write(res)
file1.close()